name: Build and Test

on:
  push:
    branches: [ main, minimal-vcpkg-example ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Cache vcpkg
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/vcpkg
          !${{github.workspace}}/vcpkg/buildtrees
          !${{github.workspace}}/vcpkg/packages
          !${{github.workspace}}/vcpkg/downloads
        key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
        restore-keys: |
          ${{ runner.os }}-vcpkg-

    - name: Install dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build
        cmake --version
        ninja --version
        gcc --version
        g++ --version

    - name: Install dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install cmake ninja boost
        cmake --version
        ninja --version
        clang --version

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: '3508985146f1b1d248c67ead13f8f54be5b4f5da'
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Configure CMake
      run: |
        if [ "${{ runner.os }}" == "macOS" ]; then
          export BOOST_ROOT=$(brew --prefix boost)
        fi
        cmake -B ${{github.workspace}}/build -G Ninja -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f "./minimal_example" ]; then
          ./minimal_example
        else
          echo "Executable not found. Build may have failed."
          exit 1
        fi

    - name: Upload build logs
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: build-logs-${{ matrix.os }}
        path: ${{ github.workspace }}/build/CMakeFiles/CMakeError.log
